id: P008020
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB20790
  title: བཀའ་བརྒྱུད་ཆོས་འབྱུང་རིན་པོ་ཆེ་སྤུངས་པའི་འོད་སྟོང་འཁྱིལ་བ
  author: ''
  volumes:
    f04dd96adeed4bfbab698bab44c09e33:
      image_group_id: I1PD34874
      title: ''
      volume_number: 1
      total_pages: 176
ebook_metadata:
  title: བཀའ་བརྒྱུད་ཆོས་འབྱུང་རིན་པོ་ཆེ་སྤུངས་པའི་འོད་སྟོང་འཁྱིལ་བ
  author: ''
  sku: P008020
  cover: cover.jpg
  layers:
  - pagination
