id: I924E9249
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:04:35+00:00'
last_modified: '2022-06-08T17:51:59.316398+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB20790
  title: བཀའ་བརྒྱུད་ཆོས་འབྱུང་རིན་པོ་ཆེ་སྤུངས་པའི་འོད་སྟོང་འཁྱིལ་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BB36:
      image_group_id: I1PD34874
      title: Volume 1 of bka' brgyud chos 'byung rin po che spungs pa'i 'od stong
        'khyil ba
      total_pages: 176
      order: 1
      base_file: BB36.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
